### ISSUE TITLE
Create a new UI element that combines the two pickers

### ISSUE THREAD

**Issue by tgpetrov** [NativeScript/nativescript-datetimepicker#18]
Add a new UI Element that combines the existing DatePickerField and TimePickerField. This will ease the usage of date/time picking in various forms where usually there is a single property in the view model. With the current setup, this one property has to be bound with 2 UI elements (one DatePickerField and one TimePickerField) which can turn tricky, for example when used in Angular Forms.

**Comment by DimitarTodorov** [comment]
https://github.com/NativeScript/nativescript-datetimepicker/releases/tag/v1.2.0
