### ISSUE TITLE
[Ipad] DateTimePicker popup is empty

### ISSUE THREAD

**Issue by kefahB** [NativeScript/nativescript-datetimepicker#20]
Hi,

I work for the first time on a Ipad project .. when i tap on `DatePickerField` or `TimePickerField` the popup is empty .. I try also to open popup from `view-model` "programmatically" and I receive same result.

![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2019-05-13 at 08 09 27](https://user-images.githubusercontent.com/18148534/57599352-a822c900-7556-11e9-97b9-bc0bcc0f9eb2.png)

**Comment by tgpetrov** [comment]
@kefahB 
What is the model, OS version and screen size for this iPad?

**Comment by kefahB** [comment]
Hi @tgpetrov 
Sorry for my late response .. is Ipad 12.9 inch

**Comment by tgpetrov** [comment]
Thanks @kefahB 
I managed to reproduce the issue.

**Comment by jorwoody** [comment]
I also reproduced this issue. I noticed that there is actually information in the popup... but it is moved far to the right. See attached screenshot taken from iPad 6th generation simulator:
https://imgur.com/a/rTmsIqV

**Comment by zbranzov** [comment]
Released in version 1.2.1
