### ISSUE TITLE
Set date month by new Date() object is not equal to the month displayed in the datepicker

### ISSUE THREAD

**Issue by ghost** [NativeScript/nativescript-datetimepicker#33]
I am setting selected date into datepicker by:

public selectedDate: Date = new Date(2014,2,23);

and then using this variable in html datepicker

<DatePickerField [(ngModel)]="selectedDate" locale="pl_PL" class="input"></DatePickerField>

The result date is not 2014.02.23 but 2014.03.23 -> the datepicker set allways one moth plus.

I am using nativescript angular template and I have installed the 1.2.1 version of datepicker plugin

**Comment by tgpetrov** [comment]
Hi @letsgoforaride 
This is expected - in JavaScript dates have their months represented by a value from 0 to 11 as demonstrated [here](https://www.w3schools.com/js/js_dates.asp). You can just `console.log(selectedDate);` and verify that this code `new Date(2014,2,23)` creates the date 23rd of March, 2014. 

Please note that when you create a date in xml/html, another `Date` constructor is used, where months are represented as you would expect ([between 1 and 12](https://www.w3schools.com/jsref/jsref_parse.asp)). For example `console.log(new Date("2019/02/24"));` would print 24th of February, 2019.
