### ISSUE TITLE
On iOS 13 the text color doesn't work, and without any style it looks like transparent text

### ISSUE THREAD

**Issue by darkyelox** [NativeScript/nativescript-datetimepicker#53]
### The problem
On iOS 13 there is a transparency of the colors that is not present in iOS 12, that makes also a problem when we try to use CSS classes for customize the component

iOS 12:
![image](https://user-images.githubusercontent.com/8183191/66968782-5a057a80-f04c-11e9-9b2a-8bb8c953fbb8.png)

iOS 13:
![image](https://user-images.githubusercontent.com/8183191/66968799-6db0e100-f04c-11e9-9a9a-dd57690b6bc0.png)

### Which platform(s) does your issue occur on?
- iOS 13 device iPhone X

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.1.2
- Cross-platform modules: 6.1.2
- Runtime(s): iOS 6.1.1
- Plugin(s): 
"dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/http": "8.0.0-beta.10",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "class-transformer": "^0.1.9",
    "class-validator": "^0.8.5",
    "clone": "^2.1.1",
    "fast-deep-equal": "^2.0.1",
    "filename-regex": "^2.0.1",
    "human-format": "^0.10.1",
    "libphonenumber-js": "^1.4.6",
    "lodash.difference": "^4.5.0",
    "lodash.has": "^4.5.2",
    "lodash.isnil": "^4.0.0",
    "lodash.last": "^3.0.0",
    "lodash.merge": "^4.6.1",
    "lodash.mergewith": "^4.6.1",
    "lodash.padstart": "^4.6.1",
    "lodash.random": "^3.2.0",
    "lodash.remove": "^4.7.0",
    "lodash.values": "^4.3.0",
    "moment": "^2.24.0",
    "moment-duration-format": "^2.2.2",
    "nativescript-advanced-webview": "^3.0.2",
    "nativescript-angular": "^8.2.1",
    "nativescript-audio": "file:../plugins/nativescript-audio/publish/package/nativescript-audio-5.0.1.tgz",
    "nativescript-bottom-navigation": "^1.3.0",
    "nativescript-calendar": "^2.0.1",
    "nativescript-datetimepicker": "^1.2.1",
    "nativescript-downloader": "file:../plugins/nativescript-downloader/publish/package/nativescript-downloader-2.1.4.tgz",
    "nativescript-drop-down": "^4.0.1",
    "nativescript-email": "^1.5.3",
    "nativescript-fancyalert": "^3.0.6",
    "nativescript-feedback": "^1.3.5",
    "nativescript-http-formdata": "^1.6.0",
    "nativescript-image-cache": "^1.1.6",
    "nativescript-imagecropper": "^1.0.5",
    "nativescript-imagepicker": "^6.1.2",
    "nativescript-intl": "^3.0.0",
    "nativescript-iqkeyboardmanager": "^1.4.0",
    "nativescript-local-notifications": "^3.1.2",
    "nativescript-localize": "^4.1.1",
    "nativescript-masked-text-field": "^4.0.1",
    "nativescript-material-bottomsheet": "^2.4.2",
    "nativescript-ng-ripple": "^2.0.1",
    "nativescript-orientation": "^2.2.1",
    "nativescript-pager": "^11.0.9",
    "nativescript-permissions": "^1.2.3",
    "nativescript-plugin-firebase": "^10.0.0",
    "nativescript-purchase": "^2.0.11",
    "nativescript-rater": "^2.1.0",
    "nativescript-sqlite": "^2.3.3",
    "nativescript-sqlite-commercial": "file:nativescript-sqlite-commercial-1.3.2.tgz",
    "nativescript-star-ratings": "file:../plugins/nativescript-star-ratings/publish/package/nativescript-star-ratings-1.0.0.tgz",
    "nativescript-telephony": "^1.0.4",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-tslib": "^1.9.1-r1",
    "nativescript-ui-autocomplete": "5.0.0",
    "nativescript-ui-calendar": "5.0.0",
    "nativescript-ui-chart": "^6.0.0",
    "nativescript-ui-gauge": "5.0.0",
    "nativescript-ui-listview": "^7.0.4",
    "nativescript-ui-sidedrawer": "7.0.0",
    "ngx-custom-validators": "^6.1.0",
    "ngx-moment": "^3.1.0",
    "pauseable": "^0.3.1",
    "reflect-metadata": "~0.1.10",
    "rx-singleton-lock": "^1.1.1",
    "rxjs": "^6.4.0",
    "tns-core-modules": "^6.1.2",
    "typeorm": "file:../../../../typescript/typeorm/build/package",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@nativescript/schematics": "~0.5.0",
    "@ngtools/webpack": "~8.2.0",
    "@types/node": "^11.13.0",
    "csv": "^5.1.1",
    "decompress": "^4.2.0",
    "download": "^7.1.0",
    "nativescript-dev-webpack": "^1.2.0",
    "nativescript-environments": "file:../plugins/nativescript-environments/publish/package/nativescript-environments-1.0.0.tgz",
    "node-sass": "4.12.0",
    "promisepipe": "^3.0.0",
    "sqlite": "^3.0.0",
    "sqlite3": "^4.0.6",
    "tns-platform-declarations": "6.0.1",
    "ts-loader": "^5.3.3",
    "typescript": "~3.5.3",
    "unzipper": "^0.9.8"
  }

### Please, tell us how to recreate the issue in as much detail as possible. 
Use the plugin as it is on iOS 13

**Comment by zbranzov** [comment]
The fix is released in nativescript-datetimepicker@1.2.2.
