### ISSUE TITLE
DatePicker exceeds the size (calendar)

### ISSUE THREAD

**Issue by juniorschen** [NativeScript/nativescript-datetimepicker#62]
Basically when using the datepicker in calendar mode it exceeds the size:
![image](https://user-images.githubusercontent.com/46031261/77202245-b45ba900-6acc-11ea-872b-79837799f290.png)

### Which platform(s) does your issue occur on?
Android emulator: PIXEL  3a XL;

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it): 6.4.1
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project): "tns-core-modules": "~6.4.0"
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project): "tns-android": {
            "version": "6.4.1"
        }
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here):
"nativescript-datetimepicker": "^1.2.2",
"nativescript-datetimepicker": {
            "version": "1.2.2",

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.
I just added the module, and add tag in my html

![image](https://user-images.githubusercontent.com/46031261/77202541-4cf22900-6acd-11ea-9f5c-7fb556308aa1.png)

![image](https://user-images.githubusercontent.com/46031261/77202565-58ddeb00-6acd-11ea-9265-8e44ebd5fb84.png)

**Comment by juanbonoso** [comment]
Having the same issue.

**Comment by Whip** [comment]
How did you get the calendar mode?

**Comment by juniorschen** [comment]
> How did you get the calendar mode?

This is shown depending on the internal configuration of the phone

**Comment by kapil9-10** [comment]
bro i got 
There is no appropriate source code format in 'C:/Users/shama/TravelGo/node_modules/nativescript-datetimepicker' entry-point. 
error in this can you please help me
or Give me suggestion for alternative

**Comment by juniorschen** [comment]
@kapil9-10 
In my case I used a modal with the datepicker of the nativescript ui:
https://docs.nativescript.org/angular/ui/ng-components/date-picker

**Comment by kapil9-10** [comment]
thanks @juniorschen

**Comment by gnanasurya19** [comment]
> [@kapil9-10](https://github.com/kapil9-10) In my case I used a modal with the datepicker of the nativescript ui: [docs.nativescript.org/angular/ui/ng-components/date-picker](https://docs.nativescript.org/angular/ui/ng-components/date-picker)

Hi, I'm having the same issue. Can you tell me how to resolve it? The link is not available right now.
