### ISSUE TITLE
Unrecognized selector sent to instance in iOS14 beta

### ISSUE THREAD

**Issue by eriese** [NativeScript/nativescript-datetimepicker#69]
### Which platform(s) does your issue occur on?
- iOS/Android/Both: **iOS**
- iOS/Android versions: **iOS14**
- emulator or device. What type of device? **both. any devices running iOS14**

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it) **6.7.8**
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project) **6.5.10**
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project) **iOS@6.5.2**
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here) 
```
"dependencies": {
    "@nativescript/theme": "~2.3.0",
    "nativescript-datetimepicker": "^1.2.2",
    "tns-core-modules": "~6.5.0"
  },
  "devDependencies": {
    "nativescript-dev-webpack": "~1.5.0"
  },
```

### Please, tell us how to recreate the issue in as much detail as possible. 
1. download [sample](https://github.com/NativeScript/nativescript-datetimepicker/files/4927453/iOS14_example.zip). unzip and run `npm install`
2. download [xcode12-beta2](https://developer.apple.com/xcode/) (I think you need to be enrolled in the Apple Developer Program to do this, which sucks)
3. run `DEVELOPER_DIR=/Applications/Xcode-beta.app/Contents/Developer tns debug ios` in terminal (you may have to open a simulator running iOS14 first)
5. click on the field to try to open it
6. see that field does not open a picker
7. find the following error in the log:
```
CONSOLE LOG file:///app/vendor.js:53426:24: DatePickerField Error: Error: -[_UIDatePickerIOSCompactView _setTextColor:]: unrecognized selector sent to instance 0x7fb421412f00
```

### Is there any code involved? 
 I tracked it down to `_applyDialogSpinnersColors` here. Both selectors throw the error:

https://github.com/NativeScript/nativescript-datetimepicker/blob/d9a965f98b22774167582544273be7391c4d3dd9/src/datetimepicker.ios.ts#L180-L181
My guess is that since you're accessing private scope in `_applyDialogSpinnersColors`, they broke it in iOS14 and either another workaround is needed, or at the very least a `try/catch`

**Comment by zghotlawala** [comment]
Yup, It is happening. Anyone found workaround or alternate solution?

**Comment by SergeyMell** [comment]
Same issue for me on iOS 14 released

**Comment by JCFowler** [comment]
Also have this issue. 

So Time picker completely breaks any app thats running on iOS 14?

**Comment by SergeyMell** [comment]
The solution from [this thread](https://github.com/NativeScript/NativeScript/issues/8862) helped me.

**Comment by asharghi** [comment]
A PR is submitted to fix this https://github.com/NativeScript/NativeScript/pull/8876
