### ISSUE TITLE
Crash on selection on iOS versions below 14 after latest iOS 14 hotfix

### ISSUE THREAD

**Issue by AnthonyLenglet** [NativeScript/nativescript-datetimepicker#78]
### Which platform(s) does your issue occur on?
- iOS
- iOS 13.7, 12.4, anything below iOS 14
- emulator and device

### Please, provide the following version numbers that your issue occurs with:
- Plugin(s): 1.2.3

### Please, tell us how to recreate the issue in as much detail as possible. 

Trying to open the datepicker was fixed in iOS 14, but the fix broke every other iOS versions apparently, we're getting a huge flood of error with it

I'm thinking it might be due to this line, since `color.ios` turned into `color` for no real explanation, and the core-module still has an ios getter from what I've seen
```
-            nativePicker.setValueForKey(color.ios, "textColor");
+            if (this.SUPPORT_TEXT_COLOR) {
+                nativePicker.setValueForKey(color, 'textColor');
+            }
```

**Comment by AnthonyLenglet** [comment]
Xcode compilation with this test fix was happening as I was filling this:
```ts
            if (this.SUPPORT_TEXT_COLOR) {
                nativePicker.setValueForKey(color.ios, 'textColor');
            }
```

and I can confirm that this fixes the issue on iOS versions below 14 while still working under iOS 14, will make a PR ASAP !

**Comment by mhtghn** [comment]
@NathanWalker this issue is still there on NS 6 version of this plugin.
I cant upgrade to NS 7 due to some plugins not compatible yet.

Can you please fix it for NS 6 app as well ?

**Comment by AnthonyLenglet** [comment]
> @NathanWalker this issue is still there on NS 6 version of this plugin.
> I cant upgrade to NS 7 due to some plugins not compatible yet.
> 
> Can you please fix it for NS 6 app as well ?

thats odd, since I am using NS6 still, and the issue has been fixed on our end

**Comment by mhtghn** [comment]
Weird can you double check that you are using NS6 please, and which version of the plugin you have.

Im using the latest 1.2.3 and you can also see that the fix you provided in your PR has not been applied.
[https://github.com/NativeScript/nativescript-datetimepicker/blob/e35391ee31b1907bd6fd595c9e45cd48d80f3965/src/datetimepicker.ios.ts#L192](https://github.com/NativeScript/nativescript-datetimepicker/blob/e35391ee31b1907bd6fd595c9e45cd48d80f3965/src/datetimepicker.ios.ts#L192)

**Comment by AnthonyLenglet** [comment]
yep nevermind, the PR isn't closed yet
https://github.com/NativeScript/nativescript-datetimepicker/pull/79

We have a local copy of the library that we built ourselves, didn't realise it wasn't merged yet, sorry !
