### ISSUE TITLE
Is this repo abandoned?

### ISSUE THREAD

**Issue by srokatonie** [NativeScript/nativescript-datetimepicker#83]
Hi, 

1. No answer to people raising issues, for example, https://github.com/NativeScript/nativescript-datetimepicker/issues/73 which has been encountered by name - it's still there since August (actually have exactly same issue)

2. Try running your angular demo - it will not work

3. I understand that the version for NS7 works, but many other plugins are not compatible with NS7, so many of us cannot migrate yet.

**Comment by NathanaelA** [comment]
Sorry, @srokatonie - All the code from this repo was moved to: https://github.com/NativeScript/plugins/
It should be working in NS7.

**Comment by srokatonie** [comment]
@NathanaelA Thanks for a quick reply. How about users using NS6 that migration is not possible yet, but official plugins are not working?  It looks like NS7 is not fully rolled out, there are no official docs even

**Comment by NathanaelA** [comment]
NS7 is fully rolled out; we are currently using it in any new applications (and any apps that clients want migrated ) in a day to day usage.   The Docs will be getting a revamp/update in early 2021.   However 99% of the docs for NS6 are still work exactly the same in NS7.     In addition you can continue to use the NS7 CLI to build NS 6 apps.   

---

All the official plugins (and many unofficial) should already be working, however they changed names spaces to actually be in the same name space as nativescript; so if the plugin used to be called:
`nativescript-datetimepicker`; it is now called `@nativescript/datetimepicker` -
https://www.npmjs.com/package/@nativescript/datetimepicker
